---
#HEADER SECTION
- name: "Play 1- cgi website configuration"  
  hosts: webservers
  become: yes
  vars:
    packages: ['tree','vim','tar','telnet','bind-utils','wget','httpd','git']

#TASK SECTION
  tasks:
    - name: Install important packages
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
      when: ansible_os_family == "RedHat"
      tags: install

        
    - name: "Create a directory - doc root"
      file:
        path: /var/www/html/learnwithproject.com
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: "Configure Apache with docroot & Timeout 300 secs"
      copy:
        src: /etc/ansible/template/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        owner: root
        group: root
        mode: '0644'
    
    - name: "code copy"
      git:
        repo: 'https://github.com/mailrahulsre/learnwithprojects.com.git'
        dest: /var/www/html/learnwithproject.com
        version: master
        force: yes

    - name: "reload"
      service:
        name: httpd
        state: reloaded
    - name: service start
      service:
        name:  httpd
        state: started
        enabled: yes
      tags: service_started

